before:
  hooks:
    - make clean
    - sh -c "NEXT_PUBLIC_VERSION={{ .Version}} make build-admin"
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/lynx
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: lorenzocamilli
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/lorenzocamilli/lynx
    description: An HTTP toolkit for security research.
    license: MIT
    commit_author:
      name: Lorenzo Camilli
      email: miosolospotify@gmail.com
    test: |
      system "#{bin}/lynx -v"

snapcrafts:
  - publish: true
    summary: An HTTP toolkit for security research.
    description: |
      Lynx is an HTTP toolkit for security research. It aims to become an open
      source alternative to commercial software like Burp Suite Pro, with
      powerful features tailored to the needs of the infosec and bug bounty
      community.
    grade: stable
    confinement: strict
    license: MIT
    apps:
      lynx:
        command: lynx
        plugs: ["network", "network-bind"]

scoop:
  bucket:
    owner: lorenzocamilli
    name: scoop-bucket
  commit_author:
    name: Lorenzo Camilli
    email: miosolospotify@gmail.com
  homepage: https://github.com/lorenzocamilli/lynx
  description: An HTTP toolkit for security research.
  license: MIT

dockers:
  - extra_files:
    - go.mod
    - go.sum
    - pkg
    - cmd
    - admin
    image_templates:
    - "ghcr.io/lorenzocamilli/lynx:{{ .Version }}"
    - "ghcr.io/lorenzocamilli/lynx:{{ .Major }}"
    - "ghcr.io/lorenzocamilli/lynx:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/lorenzocamilli/lynx:latest"
    - "lorenzocamilli/lynx:{{ .Version }}"
    - "lorenzocamilli/lynx:{{ .Major }}"
    - "lorenzocamilli/lynx:{{ .Major }}.{{ .Minor }}"
    - "lorenzocamilli/lynx:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source=https://github.com/lorenzocamilli/lynx"
    - "--build-arg=LYNX_VERSION={{.Version}}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
