name: Lint
on: [push, pull_request]
defaults:
  run:
    working-directory: ./admin
jobs:
  lint-admin:
    runs-on: ubuntu-latest
    name: Admin (Next.js)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install --legacy-peer-deps
      - run: npm run lint
